"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-21 19:10:57.218310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_routing",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "extraction_cache",
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("extracted_json", sa.JSON(), nullable=False),
        sa.Column("llm_model", sa.String(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "kids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("interests", sa.JSON(), nullable=False),
        sa.Column("availability", sa.JSON(), nullable=False),
        sa.Column("max_distance_mi", sa.Float(), nullable=True),
        sa.Column("alert_score_threshold", sa.Float(), nullable=False),
        sa.Column("alert_on", sa.JSON(), nullable=False),
        sa.Column("school_weekdays", sa.JSON(), nullable=False),
        sa.Column("school_time_start", sa.Time(), nullable=True),
        sa.Column("school_time_end", sa.Time(), nullable=True),
        sa.Column("school_year_ranges", sa.JSON(), nullable=False),
        sa.Column("school_holidays", sa.JSON(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("adapter", sa.String(), nullable=False),
        sa.Column("needs_browser", sa.Boolean(), nullable=False),
        sa.Column("crawl_hints", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("default_cadence_s", sa.Integer(), nullable=False),
        sa.Column("muted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worker_heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("worker_name", sa.String(), nullable=False),
        sa.Column("last_beat", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("changes_detected", sa.Integer(), nullable=False),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("llm_cost_usd", sa.Float(), nullable=False),
        sa.Column("error_text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "household_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("home_location_id", sa.Integer(), nullable=True),
        sa.Column("default_max_distance_mi", sa.Float(), nullable=True),
        sa.Column("digest_time", sa.String(), nullable=False),
        sa.Column("quiet_hours_start", sa.String(), nullable=True),
        sa.Column("quiet_hours_end", sa.String(), nullable=True),
        sa.Column("daily_llm_cost_cap_usd", sa.Float(), nullable=False),
        sa.Column("smtp_config_json", sa.JSON(), nullable=True),
        sa.Column("ha_config_json", sa.JSON(), nullable=True),
        sa.Column("ntfy_config_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["home_location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("last_fetched", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "watchlist_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kid_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("ignore_hard_gates", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kid_id"], ["kids.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offerings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("program_type", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("days_of_week", sa.JSON(), nullable=False),
        sa.Column("time_start", sa.Time(), nullable=True),
        sa.Column("time_end", sa.Time(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_url", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("muted_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_offerings_normalized_name"), "offerings", ["normalized_name"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("kid_id", sa.Integer(), nullable=True),
        sa.Column("offering_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("dedup_key", sa.String(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["kid_id"], ["kids.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["offering_id"], ["offerings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_dedup_key"), "alerts", ["dedup_key"], unique=False)
    op.create_index(op.f("ix_alerts_scheduled_for"), "alerts", ["scheduled_for"], unique=False)
    op.create_index(op.f("ix_alerts_type"), "alerts", ["type"], unique=False)
    op.create_index("ix_alerts_unsent_due", "alerts", ["scheduled_for", "sent_at"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kid_id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kid_id"], ["kids.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offering_id"], ["offerings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enrollments_kid_id"), "enrollments", ["kid_id"], unique=False)
    op.create_index(
        op.f("ix_enrollments_offering_id"), "enrollments", ["offering_id"], unique=False
    )
    op.create_table(
        "matches",
        sa.Column("kid_id", sa.Integer(), nullable=False),
        sa.Column("offering_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kid_id"], ["kids.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offering_id"], ["offerings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("kid_id", "offering_id"),
    )
    op.create_table(
        "unavailability_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kid_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("days_of_week", sa.JSON(), nullable=False),
        sa.Column("time_start", sa.Time(), nullable=True),
        sa.Column("time_end", sa.Time(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("source_enrollment_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kid_id"], ["kids.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_enrollment_id"], ["enrollments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unavailability_blocks_kid_id"), "unavailability_blocks", ["kid_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unavailability_blocks_kid_id"), table_name="unavailability_blocks")
    op.drop_table("unavailability_blocks")
    op.drop_table("matches")
    op.drop_index(op.f("ix_enrollments_offering_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_kid_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index("ix_alerts_unsent_due", table_name="alerts")
    op.drop_index(op.f("ix_alerts_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_scheduled_for"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_dedup_key"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_offerings_normalized_name"), table_name="offerings")
    op.drop_table("offerings")
    op.drop_table("watchlist_entries")
    op.drop_table("pages")
    op.drop_table("household_settings")
    op.drop_table("crawl_runs")
    op.drop_table("worker_heartbeat")
    op.drop_table("sites")
    op.drop_table("locations")
    op.drop_table("kids")
    op.drop_table("extraction_cache")
    op.drop_table("alert_routing")
    # ### end Alembic commands ###
