/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as KidsIndexRouteImport } from './routes/kids.index'
import { Route as SitesIdRouteImport } from './routes/sites.$id'
import { Route as KidsNewRouteImport } from './routes/kids.new'
import { Route as KidsIdWatchlistRouteImport } from './routes/kids.$id.watchlist'
import { Route as KidsIdMatchesRouteImport } from './routes/kids.$id.matches'
import { Route as KidsIdEditRouteImport } from './routes/kids.$id.edit'
import { Route as KidsIdCalendarRouteImport } from './routes/kids.$id.calendar'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIndexRoute = KidsIndexRouteImport.update({
  id: '/kids/',
  path: '/kids/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsNewRoute = KidsNewRouteImport.update({
  id: '/kids/new',
  path: '/kids/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIdWatchlistRoute = KidsIdWatchlistRouteImport.update({
  id: '/kids/$id/watchlist',
  path: '/kids/$id/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIdMatchesRoute = KidsIdMatchesRouteImport.update({
  id: '/kids/$id/matches',
  path: '/kids/$id/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIdEditRoute = KidsIdEditRouteImport.update({
  id: '/kids/$id/edit',
  path: '/kids/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIdCalendarRoute = KidsIdCalendarRouteImport.update({
  id: '/kids/$id/calendar',
  path: '/kids/$id/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/kids/new': typeof KidsNewRoute
  '/sites/$id': typeof SitesIdRoute
  '/kids/': typeof KidsIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/kids/$id/calendar': typeof KidsIdCalendarRoute
  '/kids/$id/edit': typeof KidsIdEditRoute
  '/kids/$id/matches': typeof KidsIdMatchesRoute
  '/kids/$id/watchlist': typeof KidsIdWatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/kids/new': typeof KidsNewRoute
  '/sites/$id': typeof SitesIdRoute
  '/kids': typeof KidsIndexRoute
  '/sites': typeof SitesIndexRoute
  '/kids/$id/calendar': typeof KidsIdCalendarRoute
  '/kids/$id/edit': typeof KidsIdEditRoute
  '/kids/$id/matches': typeof KidsIdMatchesRoute
  '/kids/$id/watchlist': typeof KidsIdWatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/kids/new': typeof KidsNewRoute
  '/sites/$id': typeof SitesIdRoute
  '/kids/': typeof KidsIndexRoute
  '/sites/': typeof SitesIndexRoute
  '/kids/$id/calendar': typeof KidsIdCalendarRoute
  '/kids/$id/edit': typeof KidsIdEditRoute
  '/kids/$id/matches': typeof KidsIdMatchesRoute
  '/kids/$id/watchlist': typeof KidsIdWatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/kids/new'
    | '/sites/$id'
    | '/kids/'
    | '/sites/'
    | '/kids/$id/calendar'
    | '/kids/$id/edit'
    | '/kids/$id/matches'
    | '/kids/$id/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/kids/new'
    | '/sites/$id'
    | '/kids'
    | '/sites'
    | '/kids/$id/calendar'
    | '/kids/$id/edit'
    | '/kids/$id/matches'
    | '/kids/$id/watchlist'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/kids/new'
    | '/sites/$id'
    | '/kids/'
    | '/sites/'
    | '/kids/$id/calendar'
    | '/kids/$id/edit'
    | '/kids/$id/matches'
    | '/kids/$id/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  KidsNewRoute: typeof KidsNewRoute
  SitesIdRoute: typeof SitesIdRoute
  KidsIndexRoute: typeof KidsIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
  KidsIdCalendarRoute: typeof KidsIdCalendarRoute
  KidsIdEditRoute: typeof KidsIdEditRoute
  KidsIdMatchesRoute: typeof KidsIdMatchesRoute
  KidsIdWatchlistRoute: typeof KidsIdWatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/': {
      id: '/kids/'
      path: '/kids'
      fullPath: '/kids/'
      preLoaderRoute: typeof KidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/new': {
      id: '/kids/new'
      path: '/kids/new'
      fullPath: '/kids/new'
      preLoaderRoute: typeof KidsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$id/watchlist': {
      id: '/kids/$id/watchlist'
      path: '/kids/$id/watchlist'
      fullPath: '/kids/$id/watchlist'
      preLoaderRoute: typeof KidsIdWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$id/matches': {
      id: '/kids/$id/matches'
      path: '/kids/$id/matches'
      fullPath: '/kids/$id/matches'
      preLoaderRoute: typeof KidsIdMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$id/edit': {
      id: '/kids/$id/edit'
      path: '/kids/$id/edit'
      fullPath: '/kids/$id/edit'
      preLoaderRoute: typeof KidsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$id/calendar': {
      id: '/kids/$id/calendar'
      path: '/kids/$id/calendar'
      fullPath: '/kids/$id/calendar'
      preLoaderRoute: typeof KidsIdCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  KidsNewRoute: KidsNewRoute,
  SitesIdRoute: SitesIdRoute,
  KidsIndexRoute: KidsIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
  KidsIdCalendarRoute: KidsIdCalendarRoute,
  KidsIdEditRoute: KidsIdEditRoute,
  KidsIdMatchesRoute: KidsIdMatchesRoute,
  KidsIdWatchlistRoute: KidsIdWatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
